# Generated by Django 5.2.6 on 2025-10-16 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventreview',
            name='one_review_per_user_per_event',
        ),
    ]
