# Generated by Django 5.2.6 on 2025-10-17 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Province', '0003_provincephoto'),
        ('events', '0002_remove_eventreview_one_review_per_user_per_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='Province.province'),
        ),
    ]
