# Generated by Django 5.2.6 on 2025-10-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attractionreview',
            name='one_review_per_user_per_attraction',
        ),
    ]
