# Generated by Django 5.2.6 on 2025-09-16 08:29

import Province.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=100, unique=True, verbose_name='Persian name')),
                ('name_en', models.CharField(blank=True, default='', max_length=100, verbose_name='English name')),
                ('capital', models.CharField(blank=True, default='', max_length=100, verbose_name='Capital city')),
                ('population', models.BigIntegerField(blank=True, null=True, verbose_name='Population')),
                ('area', models.CharField(blank=True, default='', max_length=50, verbose_name='Area (km², string)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('map_image', models.ImageField(blank=True, null=True, upload_to=Province.models.province_map_upload_path, verbose_name='Map image')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
                'ordering': ('name_fa',),
            },
        ),
    ]
