# Generated by Django 5.2.6 on 2025-09-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Province', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='population',
            field=models.CharField(blank=True, null=True, verbose_name='Population'),
        ),
    ]
