# Generated by Django 5.2.6 on 2025-09-16 23:35

import Province.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Province', '0002_alter_province_population'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvincePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Province.models.province_map_upload_path, verbose_name='Photo')),
                ('title', models.CharField(blank=True, default='', max_length=150, verbose_name='Title')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='Province.province')),
            ],
            options={
                'verbose_name': 'Province Photo',
                'verbose_name_plural': 'Province Photos',
                'ordering': ('order', '-created_at'),
            },
        ),
    ]
